In [19]:
import pandas as pd
from pathlib import Path

# папка с .data файлами
DATA_DIR = Path("/Users/user/Downloads/led+display+domain")

all_dfs = []

for file in DATA_DIR.glob("*.data"):

    try:
        # читаем csv-like файл
        df = pd.read_csv(file, header=None)

        # имя датасета
        dataset_name = file.stem

        # допустим target = последний столбец
        target_col = df.columns[-1]

        # число классов
        n_classes = df[target_col].nunique()

        # число фичей
        n_features = len(df.columns) - 1

        # фильтр
        if n_classes > n_features:

            # переименуем target
            df = df.rename(columns={target_col: "target"})

            # добавим имя датасета
            df["dataset_name"] = dataset_name

            all_dfs.append(df)

            print(
                f"added: {dataset_name} "
                f"(classes={n_classes}, features={n_features})"
            )

    except Exception as e:
        print("skip:", file.name, e)

# ==================================
# объединение
# ==================================

merged = pd.concat(all_dfs, ignore_index=True, sort=False)

merged.to_csv("yeast.csv", index=False)

print("\nSaved -> merged_dataset.csv")
print("shape:", merged.shape)

ValueError: No objects to concatenate

In [9]:
df = pd.read_csv('merged_dataset.csv')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,target,dataset_name
0,000106b_,1,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M,jsbach_chorals_harmony
1,000106b_,2,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M,jsbach_chorals_harmony
2,000106b_,3,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M,jsbach_chorals_harmony
3,000106b_,4,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M,jsbach_chorals_harmony
4,000106b_,5,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M,jsbach_chorals_harmony
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,015505b_,105,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m,jsbach_chorals_harmony
5661,015505b_,106,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m,jsbach_chorals_harmony
5662,015505b_,107,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M,jsbach_chorals_harmony
5663,015505b_,108,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M,jsbach_chorals_harmony
5664,015505b_,109,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M,jsbach_chorals_harmony

In [10]:
df['target'].nunique()

102

In [11]:
df = pd.read_csv('/Users/user/Downloads/anticancer+peptides/ACPs_Breast_cancer.csv')
df

      ID                 sequence               class
0      1    AAWKWAWAKKWAKAKKWAKAA         mod. active
1      2  AIGKFLHSAKKFGKAFVGEIMNS         mod. active
2      3    AWKKWAKAWKWAKAKWWAKAA         mod. active
3      4             ESFSDWWKLLAE         mod. active
4      5             ETFADWWKLLAE         mod. active
..   ...                      ...                 ...
944  945  YLDKEVKLIKKMGNHLTNLRRVA  inactive - virtual
945  946  YLSESVETIKKLGDHITSLKKLW  inactive - virtual
946  947          YPIVDAAMRQLTETG  inactive - virtual
947  948         YQNIVKAVQYAARKLQ  inactive - virtual
948  949            YQQQKKYLGRMTE  inactive - virtual

[949 rows x 3 columns]

In [12]:
%pip install ucimlrepo

Collecting ucimlrepo
  Using cached ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /opt/anaconda3/lib/python3.12/site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Using cached ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [13]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
yeast = fetch_ucirepo(id=110) 
  
# data (as pandas dataframes) 
X = yeast.data.features 
y = yeast.data.targets 
  
# metadata 
print(yeast.metadata) 
  
# variable information 
print(yeast.variables)

{'uci_id': 110, 'name': 'Yeast', 'repository_url': 'https://archive.ics.uci.edu/dataset/110/yeast', 'data_url': 'https://archive.ics.uci.edu/static/public/110/data.csv', 'abstract': 'Predicting the Cellular Localization Sites of Proteins', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 1484, 'num_features': 8, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['localization_site'], 'index_col': ['Sequence_Name'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1991, 'last_updated': 'Sat Oct 28 2023', 'dataset_doi': '10.24432/C5KG68', 'creators': ['Kenta Nakai'], 'intro_paper': None, 'additional_info': {'summary': 'Predicted Attribute: Localization site of protein. ( non-numeric ).\r\n\r\nThe references below describe a predecessor to this dataset and its development. They also give results (not cross-validated) for classification by a rule-based expert system with that version of the dataset.\r\n\r\nReference: "Expert Sytem for Predicting Protein Localization Sites in Gram-Negative Bacteria", Kenta Nakai & Minoru Kanehisa,  PROTEINS: Structure, Function, and Genetics 11:95-110, 1991.\r\n\r\nReference: "A Knowledge Base for Predicting Protein Localization Sites in Eukaryotic Cells", Kenta Nakai & Minoru Kanehisa, Genomics 14:897-911, 1992.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
                name     role         type demographic  \
0      Sequence_Name       ID  Categorical        None
1                mcg  Feature   Continuous        None
2                gvh  Feature   Continuous        None
3                alm  Feature   Continuous        None
4                mit  Feature   Continuous        None
5                erl  Feature   Continuous        None
6                pox  Feature   Continuous        None
7                vac  Feature   Continuous        None
8                nuc  Feature   Continuous        None
9  localization_site   Target  Categorical        None

                                         description units missing_values
0       Accession number for the SWISS-PROT database  None             no
1  McGeoch's method for signal sequence recognition.  None             no
2  von Heijne's method for signal sequence recogn...  None             no
3  Score of the ALOM membrane spanning region pre...  None             no
4  Score of discriminant analysis of the amino ac...  None             no
5  Presence of HDEL substring (thought to act as ...  None             no
6    Peroxisomal targeting signal in the C-terminus.  None             no
7  Score of discriminant analysis of the amino ac...  None             no
8  Score of discriminant analysis of nuclear loca...  None             no
9                                               None  None             no

In [15]:
y.nunique()

localization_site    10
dtype: int64

In [16]:
X

       mcg   gvh   alm   mit  erl  pox   vac   nuc
0     0.58  0.61  0.47  0.13  0.5  0.0  0.48  0.22
1     0.43  0.67  0.48  0.27  0.5  0.0  0.53  0.22
2     0.64  0.62  0.49  0.15  0.5  0.0  0.53  0.22
3     0.58  0.44  0.57  0.13  0.5  0.0  0.54  0.22
4     0.42  0.44  0.48  0.54  0.5  0.0  0.48  0.22
...    ...   ...   ...   ...  ...  ...   ...   ...
1479  0.81  0.62  0.43  0.17  0.5  0.0  0.53  0.22
1480  0.47  0.43  0.61  0.40  0.5  0.0  0.48  0.47
1481  0.67  0.57  0.36  0.19  0.5  0.0  0.56  0.22
1482  0.43  0.40  0.60  0.16  0.5  0.0  0.53  0.39
1483  0.65  0.54  0.54  0.13  0.5  0.0  0.53  0.22

[1484 rows x 8 columns]